### PR TITLE
Fix bug that caused array values to be dropped

### PR DESCRIPTION
**Pull request by richm**
@mrunge PTAL
@sandrobonazzola PTAL

### CODE REVIEW

**Comment by richm** [comment]
If you guys are ok with this I'm going to go ahead and merge.  Shirly needs this fix asap.

**Comment by mrunge** [comment]
Ideally we'd submit patches via review.rdoproject.org. We can merge the here right now, but once we'll set up a repo on review.rdoproject.org, that repo gets overwritten

**Comment by mrunge** [comment]
This is an example for adding a package to review.rdoproject.org https://review.rdoproject.org/r/#/c/7054/

**Comment by richm** [comment]
@mrunge sorry, since this wasn't a new package request I thought I could use a regular github PR

**Pull request merged**
